### ISSUE TITLE
tranform breaks when first line of required css is a /* comment */

### ISSUE THREAD

**Issue by diffalot** [zoubin/browserify-postcss#4]
I'm trying to do `browserify --transform [ browserify-postcss --inject --global ] --transform [ babelify --presets [ es2015 ] ] src | uglifyjs -c > dist/app.js`

Where I `require('leaflet/dist/leaflet.css')` from one of my files in `/src` but i keep getting an error about `Unterminated string constant (1:47)`

Then I can get browserify to work by going into `node_modules/leaflet/dist/leaflet.css` and removing the first couple of lines (a /\* comment */ and a blank line).

https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css

**Comment by zoubin** [comment]
I have added a comment line in `example/src/entry.css` and it works fine on both Mac and Windows.
Also, I have fixed some bugs in 0.3.3. You can try it.
